services:
  api_gateway:
    container_name: api_gateway
    build: ./http-api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: yarn run start:dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
            - dist/
        - action: sync
          path: ./test
          target: /app/test
        - action: rebuild
          path: package.json
        - action: rebuild
          path: yarn.lock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 15s
      timeout: 3s
      retries: 3
    environment:
      - PORT=3000
    depends_on:
      nats:
        condition: service_started
      users_microservice:
        condition: service_healthy
      payments_microservice:
        condition: service_healthy

  users_microservice:
    container_name: users_microservice
    build: ./users-microservice
    volumes:
      - ./users-microservice/src:/usr/src/app/src
    command: yarn run start:dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
            - dist/
        - action: sync
          path: ./test
          target: /app/test
        - action: rebuild
          path: package.json
        - action: rebuild
          path: yarn.lock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 15s
      timeout: 3s
      retries: 3
    depends_on:
      nats:
        condition: service_started
    restart: unless-stopped

  payments_microservice:
    container_name: payments_microservice
    build: ./payments-microservice
    volumes:
      - ./payments-microservice/src:/usr/src/app/src
    command: yarn run start:dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
            - dist/
        - action: sync
          path: ./test
          target: /app/test
        - action: rebuild
          path: package.json
        - action: rebuild
          path: yarn.lock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 15s
      timeout: 3s
      retries: 3
    depends_on:
      nats:
        condition: service_started
    restart: unless-stopped

  nats:
    container_name: nats
    image: nats
    ports:
      - 4222:4222
    restart: always
