export interface ISettings {
  winningScore: number;
  regularSetWin: number;
  decidingSetWin: number;
  goldenSetWin: number;
  maxForeign: number;
  maxConfederation: number;
  maxSubstitution: number;
  maxVideoChallenge: number;
  maxTimeout: number;
  timeoutLength: number[];
  technicalTimeouts: unknown[];
  decidingTechnicalTimeouts: unknown[];
  technicalTimeoutLength: unknown[];
  squadSizeForSecondLibero: number;
  playersOnRoster: number;
  rotationZones: number[];
  libero: boolean;
  technicalTimeoutScoreSum: boolean;
  coinTossEachSet: boolean;
  maxPenalty: number;
  sanctionsPerSet: boolean;
  medicalAssistance: boolean;
  fixedRotations: boolean;
  variation: string;
  challengeOptions: string;
  fixedSets: boolean;
  noVideoChallengeRefunds: boolean;
  setBreaks: number[];
  trackCaptain: boolean;
  digitalSignatures: boolean;
  liberoCanServe: boolean;
  multiplePositionSubs: boolean;
  liberoPerSet: boolean;
  simpleStats: boolean;
  goldenSet: boolean;
  rosterApprovals: string[];
  resultApprovals: string[];
  remarksApprovals: string[];
  vis: boolean;
  midRallyChallenge: boolean;
  timeoutResets: unknown[];
  regularSetSideChanges: number[];
  decidingSetSideDecision: boolean;
  decidingSetSideChange: boolean;
  organiserName: unknown;
  videoChallengePerMatch: boolean;
  paraVolley: boolean;
  nonDisabledOnRoster: number;
  nonDisabledInLineup: number;
  codeOnReports: boolean;
  mediaTimeout: boolean;
  serveTimer: unknown | null;
  superPointInSet: unknown | null;
  superPointInSetDeciding: unknown | null;
}
